name: 'Vostok CI'
description: 'Vostok CI'
author: 'Vostok'
runs:
  using: 'node12'
  main: 'dist/index.js'
inputs:
  framework:
    description: 'Test framework'
    required: false
  references:
    description: 'References type'
    required: false