name: Build

on: workflow_call

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-12]
        references: [cement, nuget]
    runs-on: ${{ matrix.os }}

    steps: 
      - name: Checkout
        uses: actions/checkout@main
        with:
          path: vostok.module
          
      - name: Install .NET 6.0
        uses: actions/setup-dotnet@main
        with:
          dotnet-version: '6.0.x'          
          
      - name: Install .NET Core 2.1
        uses: actions/setup-dotnet@main
        with:
          dotnet-version: '2.1.x'
        
      - name: Build
        uses: vostok/github.ci@master
        with:
          references: ${{ matrix.references }}