name: Publish

on: workflow_call

jobs:
  publish:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
        references: [cement, nuget]
    runs-on: windows-latest
    if: ${{ github.repository_owner == 'vostok' && (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/release/')) }}
   
    steps:
      - name: Install .NET 6.0
        uses: actions/setup-dotnet@main
        with:
          dotnet-version: '6.0.x'

      - name: Publish
        uses: vostok/github.ci@master
        with: 
          key: ${{ secrets.NUGET_TOKEN }}