name: Publish

on: 
  workflow_call:
    secrets:
      token:
        required: true

jobs:
  publish:
    runs-on: windows-latest
    if: ${{ github.repository_owner == 'vostok' && (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/release/') || startsWith(github.ref, 'refs/tags/prerelease/')) }}
   
    steps:
      - name: Install .NET 6.0
        uses: actions/setup-dotnet@main
        with:
          dotnet-version: '6.0.x'

      - name: Publish
        uses: vostok/github.ci@macos
        with: 
          key: ${{ secrets.token }}