name: Test

on: 
  workflow_call:
    inputs:
      frameworks: 
        type: string
        default: '["net6.0", "netcoreapp2.1", "net471"]'
      needs-java:
        type: boolean

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
        references: [cement, nuget]
        framework: ${{ fromJSON(inputs.frameworks) }}
        exclude: 
          - os: ubuntu-latest
            framework: net48
          - os: ubuntu-latest
            framework: net471        
    runs-on: ${{ matrix.os }}
   
    steps:          
      - name: Install .NET 6.0
        uses: actions/setup-dotnet@main
        with:
          dotnet-version: '6.0.x'
          
      - name: Install .NET 5.0
        uses: actions/setup-dotnet@main
        with:
          dotnet-version: '5.0.x'
        if: ${{ contains(fromJSON(inputs.frameworks), 'net5.0') }}      
          
      - name: Install .NET Core 3.1
        uses: actions/setup-dotnet@main
        with:
          dotnet-version: '3.1.x'
        if: ${{ contains(fromJSON(inputs.frameworks), 'netcoreapp3.1') }}          
          
      - name: Install .NET Core 2.1
        uses: actions/setup-dotnet@main
        with:
          dotnet-version: '2.1.x'

      - name: Install Java SDK
        uses: actions/setup-java@v2.3.0
        with:
          distribution: 'temurin'
          java-version: '11'
        if: ${{ inputs.needs-java }}
          
      - name: Test
        uses: vostok/github.ci@master
        with:
          references: ${{ matrix.references }}
          framework: ${{ matrix.framework }}